### ISSUE TITLE
Locations should be unique

### ISSUE THREAD

**Issue by nijotz** [nijotz/goat-tower#1]
```
Traceback (most recent call last):
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./web.py", line 57, in api
    result = do_goat_things(username, command)
  File "./web.py", line 38, in do_goat_things
    engine.handle_text(user.actor.id, command)
  File "./goattower/engine.py", line 66, in handle_text
    self.run_code(actor_id, *matches[0])
  File "./goattower/engine.py", line 99, in run_code
    self.api.run_method(code.method, code.args, context)
  File "./goattower/api.py", line 29, in run_method
    getattr(self, method_name)(*json.loads(args_json_string), context=context)
  File "./goattower/api.py", line 63, in update_location
    location = self.session.query(Actor).filter(Actor.name == location).one()
  File "/var/www/goat-tower/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2702, in one
    "Multiple rows were found for one()")
```

**Comment by nijotz** [comment]
nijotz-salt ran the "migration script" more than once. Actual migrations would be good.

**Comment by nijotz** [comment]
Unique column on location name?
